var data = {
    "Battle in a Gym": "Mankey or Makuhita encounter (shiny chance)",
"Battle in a Gym 5 times": "Machop encounter (shiny chance)",
"Win a Gym Battle": "Bulbasaur, Charmander or Squirtle encounter (shiny chance)",
"Win 3 Gym Battles": "Jynx encounter",
"Win 5 Gym Battles": "Grimer encounter (shiny chance)",
"Battle in a Raid": "Meditite encounter (shiny chance)",
"Win a Level 2 or Higher Raid": "Sableye encounter (shiny chance)",
"Win a Level 3 or Higher Raid": "Omanyte encounter or Kabuto encounter (shiny chance)",
"Win 5 Raids": "Aerodactyl encounter (shiny chance)",
"Use a Super-Effective Charge Attack 7 Times": "Electabuzz encounter",
"Catch 10 Pokemon": "Magikarp encounter (shiny chance) or Teddiursa encounter",
"Catch 5 Pokemon with Weather Boost": "Vulpix or Poliwag encounter",
"Catch a Dragon-type Pokemon": "Dratini (shiny chance)",
"Catch 5 Fighting-type Pokemon": "Breloom encounter",
"Catch 5 Normal, Electric or Poison-type Pokemon": "Starmie encounter",
"Catch 5 Water-type Pokemon": "Seel encounter (shiny chance)",
"Catch 3 Electric, Poison or Normal-type Pokemon": "Plusle or Minun encounter (shiny chance)",
"Catch 5 Flying, Dark or Psychic-type Pokemon": "Poocheyna encounter (shiny chance)",
"Catch 7 Grass, Water or Fire-type Pokemon": "Growlithe encounter (shiny chance)",
"Catch 10 Ground-type Pokemon": "Diglett encounter (shiny chance)",
"Use 5 Berries while catching Pokemon": "Weepinbel encounter",
"Use 5 Nanab Berries while catching Pokemon": "Swalot encounter",
"Use 10 Pinap Berries while catching Pokemon": "Loudred encounter",
"Make 5 Great Curveball Throws in a row": "Spinda encounter",
"Make 5 Nice Throws": "Geodude encounter (shiny chance) or Voltorb encounter",
"Make 3 Great Throws": "Gastly encounter (shiny chance), Lileep encounter or Anorith encounter",
"Make 3 Great Throws in a row": "Onix encounter",
"Make 5 Great Curveball Throws in a row": "Spinda encounter",
"Make 3 Excellent Throws in a row": "Larvitar encounter (shiny chance)",
"Evolve a Pokemon": "Eevee encounter or Pidgey encounter (shiny chance)",
"Power up a Pokemon 5 times": "Bulbasaur, Charmander or Squirtle encounter (shiny chance)",
"Use an item to evolve a Pokemon": "Skamory encounter",
"Trade a Pokemon": "Drifloon encounter (shiny chance)",
"Transfer 3 Pokemon": "Shuppet encounter (shiny chance)",
"Earn 5 Candies walking with your Buddy": "Slakoth encounter",
"Send 10 Gifts to Friends": "Alolan Exeggutor encounter",
"Hatch an Egg": "Exeggcute encounter or Spoink encounter (shiny chance)",
"Hatch 3 Eggs": "Magmar encounter",
"Hatch 5 Eggs": "Chansey encounter (plus 3 Rare Candy)",
}